# Generated by Django 2.1.4 on 2019-01-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_blog_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='test',
            field=models.CharField(default='', max_length=10),
        ),
    ]
