# Generated by Django 2.1.4 on 2019-01-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_blog_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='test',
        ),
    ]
